### ISSUE TITLE
Инициализировать хранилище для todo

### ISSUE THREAD

**Issue by DmitryTsybulkin** [vdrabll/ToDo#2]
- [x]  Добавить Coredata (если не была добавлена изначально)
- [x] Описать сущность (entity) Todo (Task)
- [x] Описать `PersistanceController`:
  - [x] Инициализатор
  - [x] Функция сохранения контекста

**Comment by vdrabll** [comment]
@DmitryTsybulkin  ready to review
