### ISSUE TITLE
Сделать View со списоком Todo

### ISSUE THREAD

**Issue by DmitryTsybulkin** [vdrabll/ToDo#3]
- [x] Описать список todo view через swift:
- Должен скроллиться
- Должен соответствовать [дизайну](https://www.figma.com/file/7dPLzJJ57PvJhWOzqeWp7y/A-Simple-To-Do-App%2C-Built-with-Auto-Layout-(Community)?type=design&node-id=0%3A1&mode=design&t=PhckXS6S5KQ7irpp-1)
- [x] Сделать 2 отдельных списка для Todo и Completed: 1 запрос для списков, но в при отображении фильтровать по свойству isChecked
- [x] Данные для canvas использовать из preview

**Comment by vdrabll** [comment]
@DmitryTsybulkin ready to review
